# Generated by Django 2.2.28 on 2023-07-06 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sdyu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdbr', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sgfr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngmg', models.BigIntegerField()),
                ('bvvnse', models.BigIntegerField()),
                ('swer', models.BigIntegerField()),
                ('rel_sdyu_1_1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sgfr_rel_sdyu_1_1', to='home.Sdyu')),
            ],
        ),
    ]
